language: java
jdk:
- oraclejdk8
deploy:
- provider: s3
  access_key_id: AKIAI27RKRZTWC7LOJOQ
  secret_access_key: &1
    secure: n/D/qD5Bg2ByMr+/AfYNu1VQgKXTCgEghIgxBG65MQk0S4/N2ZDf8Sb1QvOmmDi8OP4kFLiy+QZWipSOhao90hgRsQ1+jsR9/sDUXkjd5v4d0tFNKQThBRDMtsRPKsq8ZZF0xXxqrKkwVFiDhARFARuJaenufcDv0TSTSsxTYUzlpMfPCaAdJw5C2OudSb3j4+a0VI0dDZ2a7PDnN5aeUhju9WUQUzGVi6GoiQ5GEiggvoV1oHeHEO/cFC+cekV/dpXmifghufwA3CRUCvqum/I2v3gzavO53v8p55AbcbOQDq/4wBMdv15Iq0Gd3kfhfqVY/C2Y0nRGdGOCsL47y5P4l9qJ0Y2v9fCejKZGv9QpYafMoCFbng9ZcSX3xEoHQHNaxUZogK/+5wPWrud9kmvsLDsM4PZJ8QCIomW1r7l4zslqsX1GjHx8Iu3h5wpHDzwFsFTLMcE+F3vXklgjC5DM/j7C65Or01k0707bW9h8uqumfbTcETV5FPVeP/6Ke5NRF5wDg1OEBiv0603vJJHoTVxE9zrLXAdyNtJNSgXqMX94FX2XAfGsGedtVVGSmbMW6Got15SHjwuxv125BSvCGqciYIHllvAeQVFb9MKkAgpp2HU69cTVPGUj8jw7iFVCuOpWSRQqkghOqJh5MiH0ApezwPQpQsCwWOnjFaM=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: cloudaddy/cloudaddys-project
  bucket: cloudaddy
  upload_dir: latest
- provider: codedeploy
  access_key_id: AKIAI27RKRZTWC7LOJOQ
  secret_access_key: *1
  bucket: cloudaddy
  key: latest/cloudaddy-website.zip
  bundle_type: zip
  application: Cloudaddy
  deployment_group: production
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- rm -f .gitignore
- mv target/cloudaddy-project-*.war dpl_cd_upload/cloudaddy-website.zip
