language: java
jdk:
- oraclejdk8
deploy:
  provider: codedeploy
  access_key_id: AKIAI27RKRZTWC7LOJOQ
  secret_access_key:
    secure: zGCgEXGy8aEV+EEDzF1BqYeLYt5phUVT+Zaq1r57C/YP+DeN5O/0TXK1TaOHOXEvYA+QFRiqMBMIxcIdLcHs9gOelqs30YeqgW8CJ3gts4IRQ84fm5QYXEILS48vFgZ1H+sq0xQSYVnu/R0OBgA8KJCUlE19LFZngyTjS/mrJQrrf6aLE9RGCsBltxH5IePvMKerP/UmsgalJ5L67tfgxNwzHU6DIDRi9Q+bpIO2JYlxMmfbCE1N1eq1BCM2qDZcikYPlUyE2YbFVVNjqyFAX3cKGRZItPhTtWehz1qMVbiFkdSv3sL9yRgZblRDtMXtYeHDWLHAYB9GYdNpHe0zohc0YjTf3yxNHY4l5OSX/gAOvMiiMGowuD9uMjmgXsmE8kLoFMcFFp8KCivPybj0KuuU5x3JVwxiMjDzhOkCx1u7M5/cgbubnX1eAFNY3yIKt9lNOHqInrZmNTDORlBSYbgLMMBGxUlm6YiZshy6frFlQIbulw/+x0ModHFWY0oxLQ2iPwFrTZvJBxpAKS8DCwl53gqG7IQG3nYOmjVG/glr/YvTGeUz67rAJQm5YvUerv9imqvVuYkyfa0F842jIhhWDUkgsjfWHWzO68rcQAKXpS4ibELxAa1uag0PeohaW6rc63gQwrtOPkYFFxGtPlkDf4PvqtH4BysUv0tleGc=
  bucket: cloudaddy
  key: latest/cloudaddy-website.zip
  bundle_type: zip
  application: Cloudaddy
  deployment_group: production
  on:
    repo: cloudaddy/cloudaddys-project
before_deploy:
- mkdir -p dpl_cd_upload
- ls -Rahl
- rm -f .gitignore
- mv target/cloudaddy-project-*.war dpl_cd_upload/cloudaddy-website.zip
- ls -Rahl
