language: java
jdk:
- openjdk7
deploy:
- provider: s3
  access_key_id: AKIAIWV6A4KDI5OULCPQ
  secret_access_key: &1
    secure: 2FYrGzJN8hQteYXjNKZR1QQmbj+WLr/pU1zK7YgOQFtOzQEc7lsSsa1GiDEjtAbQ3ULUmFyv6uKIc8opQKvTc59foIButiZEDhAmO8cjqBDu+qfp75CpqpXt6FmNEzWcP8yA+axlSxpbkFEDB7HMRSBlXljMuwudj4h64c4KZTxUTbcQd6BGjTVh3eLRZ8VM42TQTdtWhU3barCXmbbyKiYtOaTkUsc11jPyfLt1oXVAJqGwYU+jboLbK04FZqOBf01QXTTsQPTxVbA+eTayVufxPOX7thHjvsUVg/1To+eKukh52t9c1SuEjOmgh9F5nAHirTAEXLKtW+oOg9HXM19+FjqgdTwE46WWauWx4HaRY69CAeJjUc8+tXapbByBzjxVG5+sqTXwXbo/noVHqTxpeVnVuhMk0GuaKN6ylS5gWQDhlvqtw+X9qLqW/WUgN4xI59SisAYiauWjtSN8TVAREg/I3NUCXBFrqL4tt+IRoOoVMOXizf4HbFaGYNASSzk1UZqjFkc/uS/tNOGCDjEw2mIc6RS5ie0InXLDCDsd5oMn/U9WXt/YjMu8/q6a4BnShNzXDcIuxkYBq0usr2kltZpvbBpUSNpZ6+jDFeynIOcTbNbq6PR937qu5wSodJpqse3MU+k6UpaXN9N1wMjRBfYapvsCdjoU2lKb/WA=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: cloudaddy/cloudaddys-project
    branch: phase2
  bucket: cloudaddy-releases
  upload_dir: latest
- provider: codedeploy
  access_key_id: AKIAIWV6A4KDI5OULCPQ
  secret_access_key: *1
  bucket: cloudaddy-releases
  key: latest/cloudaddy-website.zip
  bundle_type: zip
  application: Cloudaddy
  deployment_group: production
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- rm -f .gitignore
- mkdir -p dist
- cp appspec.yml dist/
- cp -r deploy/scripts dist/
- cp target/cloudaddy-project-*.war dist/ROOT.war
- cd dist
- zip -r ../dist.zip . *
- cd ..
- cp dist.zip dpl_cd_upload/cloudaddy-website.zip
