version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: /var/lib/tomcat7/webapps
hooks:
  BeforeInstall:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 3600
