#!/bin/bash -ex
# install awscli and CodeDeploy Agent
sudo apt-get -y update
sudo apt-get -y install awscli
sudo apt-get -y install ruby2.0
cd /home/ubuntu
aws s3 cp s3://aws-codedeploy-us-east-1/latest/install . --region us-east-1
chmod +x ./install
sudo ./install auto

# install tomcat and java
sudo apt-get -y install tomcat7



exit 0
